// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.DataAccess;

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "Funcionario",
                            ConcurrencyStamp = "2",
                            Name = "Funcionario",
                            NormalizedName = "FUNCIONARIO"
                        },
                        new
                        {
                            Id = "Usuario",
                            ConcurrencyStamp = "3",
                            Name = "Usuario",
                            NormalizedName = "USUARIO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "432e0b12-6f62-4a9e-8f77-7e4c2440aa8f",
                            RoleId = "Admin"
                        },
                        new
                        {
                            UserId = "dc5214ae-d794-4da1-a4b8-4c32883a026e",
                            RoleId = "Funcionario"
                        },
                        new
                        {
                            UserId = "0414ef00-51f7-4cc5-aae8-b783ad4f3769",
                            RoleId = "Usuario"
                        },
                        new
                        {
                            UserId = "51596782-b6e5-43de-9a9b-0087a57ec613",
                            RoleId = "Usuario"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("backend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("cedula")
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("genero")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.Property<string>("primerApellido")
                        .HasColumnType("text");

                    b.Property<bool>("recibeOfertas")
                        .HasColumnType("boolean");

                    b.Property<string>("segundoApellido")
                        .HasColumnType("text");

                    b.Property<int>("tipoCedula")
                        .HasColumnType("integer");

                    b.Property<int>("tipoCuenta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "432e0b12-6f62-4a9e-8f77-7e4c2440aa8f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "330983d8-39c4-497a-a0bf-b5be751c189a",
                            Email = "admin@alcabox.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ALCABOX.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHHysBNJsqz26DN7/oUDkt+mU0ZXMCTD8fSquZG9FhKl37FOugpz6Dp50hCKzUIIog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00ad4e9a-3230-4fab-9c19-2cbd1ebca9f6",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            cedula = "11111111",
                            direccion = "Direcion Admin",
                            genero = 1,
                            nombre = "AlcaBox Admin",
                            primerApellido = "Alca",
                            recibeOfertas = false,
                            segundoApellido = "Box",
                            tipoCedula = 1,
                            tipoCuenta = 1
                        },
                        new
                        {
                            Id = "dc5214ae-d794-4da1-a4b8-4c32883a026e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2af34ab-a66e-4c46-9f6c-648b966cd61d",
                            Email = "billy@alcabox.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BILLY@ALCABOX.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENLtbroaBVGLd8PplJXprnZJ9UMQts3yYYn9GH6ojTlxhqsZ3Ot9qrT8yT7kAhxs1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13d73cdc-26f5-496c-8758-1b695b10c83b",
                            TwoFactorEnabled = false,
                            UserName = "Billy",
                            cedula = "87654321",
                            direccion = "Direcion Funcionario",
                            genero = 1,
                            nombre = "Billy",
                            primerApellido = "H",
                            recibeOfertas = false,
                            segundoApellido = "",
                            tipoCedula = 1,
                            tipoCuenta = 1
                        },
                        new
                        {
                            Id = "0414ef00-51f7-4cc5-aae8-b783ad4f3769",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "65671a1a-9ff5-4fac-a7e2-5ec8fe1c255d",
                            Email = "pablo@alcabox.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PABLO@ALCABOX.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGP0753CNzZD3cy1MY+KpGQL8v8Il6UsArn0WKbiFc86VnFkTiAr4VWxP5gbreXakQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ff8384df-9221-443d-9880-5cf9e78bb5bf",
                            TwoFactorEnabled = false,
                            UserName = "Pablo",
                            cedula = "12345678",
                            direccion = "Direcion Usuario",
                            genero = 1,
                            nombre = "Pablo J.",
                            primerApellido = "J",
                            recibeOfertas = true,
                            segundoApellido = "",
                            tipoCedula = 1,
                            tipoCuenta = 1
                        },
                        new
                        {
                            Id = "51596782-b6e5-43de-9a9b-0087a57ec613",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1764921b-c157-448c-b791-a45d3c0b4479",
                            Email = "bot@alcabox.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOT@ALCABOX.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ1eyj9nEtBMbk26vR0TFTSqg2/eO04M7rBh5wp7f3KsswKFaYPpx+dH2tqxBXa/Jg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "43149d2d-5c29-4178-a302-762b52c1eb95",
                            TwoFactorEnabled = false,
                            UserName = "Bot",
                            cedula = "55555555",
                            direccion = "Direcion Bot",
                            genero = 1,
                            nombre = "Bot R.",
                            primerApellido = "B",
                            recibeOfertas = false,
                            segundoApellido = "",
                            tipoCedula = 1,
                            tipoCuenta = 1
                        });
                });

            modelBuilder.Entity("backend.Models.Arancel", b =>
                {
                    b.Property<int>("ArancelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("ArancelId");

                    b.ToTable("Arancel");

                    b.HasData(
                        new
                        {
                            ArancelId = 1,
                            Nombre = "Arancel_1"
                        },
                        new
                        {
                            ArancelId = 2,
                            Nombre = "Arancel_2"
                        });
                });

            modelBuilder.Entity("backend.Models.BitacoraAccion", b =>
                {
                    b.Property<int>("Accion_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Accion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Usuarios")
                        .HasColumnType("text");

                    b.HasKey("Accion_Id");

                    b.HasIndex("Usuarios");

                    b.ToTable("BitacoraAccion");
                });

            modelBuilder.Entity("backend.Models.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("EstadoId");

                    b.ToTable("Estado");

                    b.HasData(
                        new
                        {
                            EstadoId = 1,
                            Nombre = "En espera a Courier"
                        },
                        new
                        {
                            EstadoId = 2,
                            Nombre = "Recibido en Courier"
                        },
                        new
                        {
                            EstadoId = 3,
                            Nombre = "En Tránsito a CR"
                        },
                        new
                        {
                            EstadoId = 4,
                            Nombre = "En vuelo"
                        },
                        new
                        {
                            EstadoId = 5,
                            Nombre = "Recibido en Aduanas"
                        },
                        new
                        {
                            EstadoId = 6,
                            Nombre = "En trámite Aduanal"
                        },
                        new
                        {
                            EstadoId = 7,
                            Nombre = "En proceso de Entrega"
                        },
                        new
                        {
                            EstadoId = 8,
                            Nombre = "Entregado"
                        },
                        new
                        {
                            EstadoId = 9,
                            Nombre = "Finalizado"
                        });
                });

            modelBuilder.Entity("backend.Models.Paquete", b =>
                {
                    b.Property<int>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ArancelId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<double>("Precio")
                        .HasColumnType("double precision");

                    b.Property<int>("Tracking")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text");

                    b.HasKey("PaqueteId");

                    b.HasIndex("ArancelId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Paquete");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.BitacoraAccion", b =>
                {
                    b.HasOne("backend.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Paquete", b =>
                {
                    b.HasOne("backend.Models.Arancel", "Arancel")
                        .WithMany()
                        .HasForeignKey("ArancelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Arancel");

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
